### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by freebumba27** [yesidlazaro/GmailBackground#10]
Error:(37, 13) Failed to resolve: com.github.yesidlazaro:GmailBackground:1.0
<a href="openFile:/Users/AJ/Downloads/abcApp/abcApp/build.gradle">Show in File</a><br> a href="open.dependency.in.project.structure"> Show in Project Structure dialog </a>

**Comment by yesidlazaro** [comment]
make sure  you have this in your build.grade
repositories {
        // ...
        maven { url "https://jitpack.io" }
 }

Make sure you didn't set Android Studio to work offline
