### ISSUE TITLE
Question - gmail max mails per time unit

### ISSUE THREAD

**Issue by MFlisar** [yesidlazaro/GmailBackground#2]
Have you tried this with high usage? It's already a long time ago, but I tried that as well. I have set up an email address for my app and used it's mail and credentials in an app. But after some time this stopped working... And I'm quite sure it was because of gmail was recognising emails were send automatically by an app/script...

I currently just have a simple php script on my own server that I just open and hand on the mail data and let the simple script send mails through my own internet host...

**Comment by ingyesid** [comment]
@MFlisar https://support.google.com/accounts/answer/6010255?hl=en
