### ISSUE TITLE
Exception instead of sending email when calling send()

### ISSUE THREAD

**Issue by Deepscorn** [yesidlazaro/GmailBackground#3]
Exception stack:

Could not connect to SMTP host: smtp.gmail.com, port: 465
11-28 09:36:11.391 10543-10587/ru.driverprofi.driverprofi W/System.err: javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465;
11-28 09:36:11.391 10543-10587/ru.driverprofi.driverprofi W/System.err:   nested exception is:
11-28 09:36:11.391 10543-10587/ru.driverprofi.driverprofi W/System.err: 	javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-28 09:36:11.392 10543-10587/ru.driverprofi.driverprofi W/System.err:     at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1391)
11-28 09:36:11.392 10543-10587/ru.driverprofi.driverprofi W/System.err:     at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:412)
11-28 09:36:11.392 10543-10587/ru.driverprofi.driverprofi W/System.err:     at javax.mail.Service.connect(Service.java:310)
11-28 09:36:11.392 10543-10587/ru.driverprofi.driverprofi W/System.err:     at javax.mail.Service.connect(Service.java:169)
11-28 09:36:11.392 10543-10587/ru.driverprofi.driverprofi W/System.err:     at javax.mail.Service.connect(Service.java:118)
11-28 09:36:11.392 10543-10587/ru.driverprofi.driverprofi W/System.err:     at javax.mail.Transport.send0(Transport.java:188)
11-28 09:36:11.392 10543-10587/ru.driverprofi.driverprofi W/System.err:     at javax.mail.Transport.send(Transport.java:118)

Code to reproduce:

BackgroundMail bm = new BackgroundMail(getActivity().getApplicationContext());
        bm.setProcessVisibility(false);
        bm.setGmailUserName(...);
        bm.setGmailPassword(...);
        bm.setMailTo(...);
        bm.setFormSubject(...);
        bm.setFormBody(...);
        bm.send();

Maybe it will help: http://developer.android.com/training/articles/security-ssl.html

**Comment by Deepscorn** [comment]
Environment: Genymotion emulator Nexus 5

**Comment by Deepscorn** [comment]
Sorry, looks like it is an emulator issue. Tried same code on real device and no exception, email sent. Closing issue

**Comment by afomich** [comment]
Hello, have the same issue. Doesn't work on emulator and device. Toast with "Check your's connection" shows.
