### ISSUE TITLE
Why there is no "cc"/"bcc" ?

### ISSUE THREAD

**Issue by evasyuk** [yesidlazaro/GmailBackground#36]
I see that BackgroundMail builder does not have setter for "cc" field.

Do I miss something or is it real opportunity to make a contribution?

**Comment by luongvo** [comment]
@evasyuk Please take a look at my fork repo at https://github.com/luongvo/GmailBackground. Currently, I just made a PR at https://github.com/yesidlazaro/GmailBackground/pull/34 and it seems @yesidlazaro does not have time to check it.

**Comment by evasyuk** [comment]
@luongvo You've made changes exactly I wanted to.
Great job! And thank you!
