### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by afomich** [yesidlazaro/GmailBackground#4]
Hello. I faced with issue when my email box (at @gmail.com) block my app by "non secure app try to use your's acc.." reason.
I changed my gmail account preferences and now it works. But is it possible solve this problem without changing google acc preferences? 
Thanks.

**Comment by afomich** [comment]
Resolved.

**Comment by lectricas** [comment]
@afomich  describe how you solved the issue

**Comment by afomich** [comment]
I change security options on my gmail. You can find it here https://support.google.com/accounts/answer/6010255?hl=en
