### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by stan2100** [yesidlazaro/GmailBackground#5]
Hi,
thank you for this great app! Could you tell me how I could send an Email from a service (like sendTestEmail() from MainActivity)? It seems, my service is missing the app context (which is required in “public BackgroundMail(Context context)” .  
Thank you very much in advance

**Comment by joe1000** [comment]
I've figured it out. :-) 
Thank you once again for your great work. 
Please close this question (issue). 
Have a great day!
