### ISSUE TITLE
Unable to import the library

### ISSUE THREAD

**Issue by srinivas69** [yesidlazaro/GmailBackground#8]
I have added this library as Gradle to my Android Studio.
But I am unable to import the library. I'm not getting any suggestions to import the library.
How to resolve this?

**Comment by server102** [comment]
paste the error you're getting

**Comment by galibimtiaz** [comment]
Error:(39, 13) Failed to resolve: com.github.yesidlazaro:GmailBackground:1.0

**Comment by Silvuz** [comment]
The same problem here. Maybe some problem uploading to maven?

**Comment by freebumba27** [comment]
@server102  any update man

**Comment by server102** [comment]
1) Undo the process you used in adding the library dependency to android studio
2) go to **Build** -> **Clean Project.** 
3) Then **File** -> **Invalidate Cache and Restart**
4) On your **Project pane**, switch the view to **Android**
5) Open **build.gradle (Module: app)** and add 
    `compile 'com.github.yesidlazaro:GmailBackground:1.0' `
to your project dependencies
6) go to **Build** -> **Rebuild Project**

**Comment by yesidlazaro** [comment]
thanks to @server102 for the explanations.

**Comment by victornaito** [comment]
**Error:(33, 14) Failed to resolve: com.github.yesidlazaro:GmailBackground:1.0**

**Comment by hamzaali6307** [comment]
unable to send mail in background. is this lib is deprecated,
"Error sending email, check your connection"  i am getting this error but my netwrkis good and other network things are working in other app i used same snippet of code working fine in past now that one also gives me error

**Comment by luongvo** [comment]
@hamzaali6307 can you try my fork instead? https://github.com/yesidlazaro/GmailBackground/issues/39
