### ISSUE TITLE
Suggestion (Broadcast Reciever)

### ISSUE THREAD

**Issue by pavle93** [yesidlazaro/GmailBackground#9]
Hi, I cam across of an issue while running your library inside the broadcast reciever. You can't attach progress bar to the window from outside of the application. So I had to take out whole that part. However it is possible to be done without carving the code too much. I just wanted to suggest waht to include in next update, cheers mate and thanks :)

**Comment by agrigio** [comment]
please can you say me how you modifies the code? I have the same issue here.

Error:
Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application

**Comment by pavle93** [comment]
Fork the library onto your computer and then remove every apperance pf progress bar.

**Comment by agrigio** [comment]
maybe i've solved by setting 		
backgroundMail.showVisibleProgress(false);

testing now...

**Comment by androidovshchik** [comment]
It's now
```.withProcessVisibility(false)```
